#
# Autogenerated by Thrift
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift/protocol'

module Color
  RED = 1
  YELLOW = 2
  GREEN = 3
  BLUE = 4
  VALID_VALUES = Set.new([RED, YELLOW, GREEN, BLUE]).freeze
end

